### ISSUE TITLE
安装报错怎么办？

### ISSUE THREAD

**Issue by leqii-com** [sentinl/sentinl#803]
root@elk /usr/share/kibana/bin# ./kibana-plugin install file:///root/sentinl-v7.6.1.zip
Attempting to transfer from file:///root/sentinl-v7.6.1.zip
Transferring 146880856 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Plugin installation was unsuccessful due to error "No kibana plugins found in archive"

如上错误，无法安装，我的kibana版本是7.13.4，是否需要一致？可是在这里没找到7.13.4版本的sentinl呀。

**Comment by HaiFeng327** [comment]
为了使用这个插件，还需要降级到和它版本匹配的elk，服了

**Comment by chenryn** [comment]
elk 内部接口一直不太稳定，每个版本都在变，所以插件维护太费劲了……有告警刚需又不想自己折腾的，要不直接花钱买商业版得了。

**Comment by lmangani** [comment]
@chenryn is right, the maintenance has unfortunately become impossible, and like everyone we abandoned Elastic. 
Check our new project [cloki](https://cloki.org)
