### ISSUE TITLE
sentinl Alarms payload.hits.hits is null

### ISSUE THREAD

**Issue by wangan0915** [sentinl/sentinl#806]
#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       |    6.5.3     |
| Elasticsearc |    6.5.3     |
| Server OS    |  NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"       |
| Browser      |     Chrome 105.0.5195.127    |

#### Original Install Method

- [ ] Release pkg link  https://github.com/sentinl/sentinl/releases/sentinl-v6.5.3.zip
- [ ] Gulp
- [ ] Source
- Other: 

#### Bug Description
query in kibana Dev Tools ,hits.hits is not null

but copy the query to sentinl watchers  ,when executed, i find data in alarms ,but hits.hits is null,

#### Steps to Reproduce
1.{
  "took" : 49,
  "timed_out" : false,
  "_shards" : {
    "total" : 123,
    "successful" : 123,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 14,
    "max_score" : 0.0,
    "hits" : [
      {
        "_index" : "cs-msgcenter-timecosts-2022.09.27",
        "_type" : "doc",
        "_id" : "x_bgfoMBDTHvbGDFjXiJ",
        "_score" : 0.0,
        "_source" : {
          "@timestamp" : "2022-09-27T12:16:56.650Z",
          "reqMethod" : "POST",
          "result" : 401,
.........
2. "hits": {
      "total": 14,
      "max_score": 0,
      "hits": []

#### Sample of data you have in Elasticsearch
```
```

#### Full Watcher JSON
```
```

#### Errors in Browser Console (if relevant)
```
```

**Comment by wangan0915** [comment]
Reproduce 1 is query in dev tools  ,2 is in sentinl alarms。

**Comment by lmangani** [comment]
Do not expect a fix. Unfortunately, nobody is sponsoring this project which is no longer maintained. #sad
It would be great to revive our work into #OpenSearch and other platforms, but unfortunately we received zero support from the community.
